# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
import json

import requests
# Form implementation generated from reading ui file '二维码.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import qrcode
import time
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 404)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 60, 391, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 140, 211, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "二维码生成"))
        self.pushButton.setText(_translate("MainWindow", "点击生成二维码"))
        self.pushButton.clicked.connect(self.but)

    def but(self):
        url = "http://httpbin.org/ip"  # 也可以直接在浏览器访问这个地址
        r = requests.get(url)  # 获取返回的值
        ip = json.loads(r.text)["origin"]  # 取其中某个字段的值
        # 发送get请求
        url = f'http://ip-api.com/json/{ip}?fields=country,city,regionName,query&lang=zh-CN'
        # 其中fields字段为定义接受返回参数，可不传；lang为设置语言，zh-CN为中文，可以传
        res = requests.get(url)  # 发送请求
        adddata = json.loads(res.text)
        txt = self.lineEdit.text()
        img = qrcode.make(txt + "\n" + time.strftime("%Y/%m/%d") + "\n" + time.strftime("%H:%M:%S") + "\n" + adddata[
            "country"] + "/" + adddata["regionName"] + "/" + adddata["city"])
        img.show()
        img.save(txt+".jpg")


if __name__ == '__main__':

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())